import {test,expect} from '@playwright/test';
import {onTheMenu} from './support/shop.js';
test('tablet basket follows selected items and notes without stealing search focus',async({page})=>{
  await page.setViewportSize({width:1024,height:1000});
  await onTheMenu(page,'nothing');
  await expect(page.locator('#cart-sheet-body')).toBeVisible();
  await page.locator('#product-search-input').fill('coffee');
  await page.locator('.btn-add[data-id="p-coffee"]').click();
  await expect(page.locator('#product-search-input')).toHaveValue('');
  await expect(page.locator('.menu-basket-lines')).toContainText('1 × Coffee');
  await page.evaluate(async()=>{await setCartItemNotes('p-coffee','No sugar <script>');await updateCart();});
  await expect(page.locator('.menu-basket-lines li').filter({hasText:'Coffee'})).toContainText('No sugar <script>');
  await page.locator('.btn-add[data-id="p-dosa"]').click();
  await expect(page.locator('.menu-basket-lines li')).toHaveCount(2);
  await expect(page.locator('.menu-basket-total')).toContainText('130');
  await expect(page.locator('.menu-basket-lines script')).toHaveCount(0);
  await page.locator('#product-search-input').fill('chicken');
  await page.evaluate(()=>updateCart());
  await expect(page.locator('#product-search-input')).toBeFocused();
  await expect(page.locator('#product-search-input')).toHaveValue('chicken');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-artifacts/menu-tablet-basket.png',fullPage:true});
  const menu=await page.locator('.content-wrapper').boundingBox(),basket=await page.locator('#cart-summary-sheet').boundingBox();
  expect(menu.x+menu.width).toBeLessThanOrEqual(basket.x+1);
  await page.setViewportSize({width:390,height:844});
  await expect(page.locator('#cart-summary-sheet')).toBeHidden();
  await page.locator('button.bill-what').click();
  await expect(page.locator('.menu-basket-lines li')).toHaveCount(2);
  await expect(page.locator('.menu-basket-lines')).toBeVisible();
  await page.screenshot({path:'test-artifacts/menu-phone-basket.png',fullPage:true,animations:'disabled'});
  await page.locator('.cart-sheet-close').click();
  await expect(page.locator('#cart-summary-sheet')).toBeHidden();
});
